### ISSUE TITLE
No brightness value for dimmer (on Wireless smart hub)

### ISSUE THREAD

**Issue by Twabi2** [filipvh/hass-nhc2#6]
Dear all,

I have two dimmer switches (551-72201) that correctly show up in HA as lights. However, they lack the brightness value, and I am unable to set it through the light.turn_on service. Is this not implemented yet?

**Comment by filipvh** [comment]
Hi @Twabi2 this is a known issue. I hope to be able to debug this next week. You are always welcome to join us on 
https://join.slack.com/t/nhc2/shared_invite/zt-j6qy16sl-kZF6V__uTCLVLpZUNutJWA

**Comment by filipvh** [comment]
@Twabi2 this should be resolved in 1.4.0-beta3.
Within the next 10 hours I hope to merge it into master and release 1.4.0 as stable.
... given no other issues arise/are found

**Comment by Twabi2** [comment]
Great news, thanks! I just installed the beta and restarted HA. However,
the lights are still showing as simple binary states, no attribute for
brightness. Should I remove and re-add the integration?

**Comment by filipvh** [comment]
That might help; but should not be an issue.
How did you install 1.4.0-beta3, because others have this working just fine.

**Comment by Twabi2** [comment]
Via HACS. Uninstalled the previous major release, reinstalled the beta,
then restarted HA.

Just to make sure that it was installed correctly, here's a screenshot from
HACS

**Comment by filipvh** [comment]
I see you have the new type of CoCo, with wireless. Missed that on your original post.
While these should be the same on the MQTT broker, someone at Niko assured me...
... did you setup the dimmer in the software? I have no idea how that process would be.
We could investigate if there are differences between your setup and a classic NHC2.
Could you join us on the slack? That would make debugging much more easy.

**Comment by filipvh** [comment]
side question, does the dimming function work properly in the Niko provided app?

**Comment by Twabi2** [comment]
Dimming works just fine in the Niko app, so that's not it. I can also dim the lights without any issues through Google Assistant. I'm on Slack on your channel since yesterday, but I have never used Slack before, so I'm not too clear on how to use it properly

**Comment by filipvh** [comment]
In the hass logs, you can click on a button to show the entire log. Does it reveal something about nhc2 ?
